# Generated by Django 4.2.3 on 2023-09-02 11:53

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocsObjects',
            fields=[
                ('id', models.CharField(default=apps.home.models.generate_random_string, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to='')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(null=True)),
                ('who_signed', models.CharField(max_length=200)),
                ('signatory_position', models.CharField(max_length=200)),
                ('signatory_workplace', models.CharField(max_length=200)),
                ('performer', models.CharField(max_length=200)),
                ('performer_position', models.CharField(max_length=200)),
                ('performer_workplace', models.CharField(max_length=200)),
                ('validity_period', models.DateField(null=True)),
                ('given_by_ERI', models.CharField(max_length=200)),
            ],
        ),
    ]
