# Generated by Django 4.2.3 on 2023-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsobjects',
            name='given_by_ERI',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docsobjects',
            name='performer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docsobjects',
            name='performer_position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docsobjects',
            name='performer_workplace',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docsobjects',
            name='signatory_position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docsobjects',
            name='signatory_workplace',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='docsobjects',
            name='validity_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docsobjects',
            name='who_signed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
