# Generated by Django 4.2.3 on 2023-09-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_docsobjects_given_by_eri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsobjects',
            name='document_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
