# Generated by Django 4.2.3 on 2023-09-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_docsobjects_document_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docsobjects',
            old_name='validity_period',
            new_name='end_ERI',
        ),
        migrations.AddField(
            model_name='docsobjects',
            name='start_ERI',
            field=models.DateField(blank=True, null=True),
        ),
    ]
