# Generated by Django 4.2.3 on 2023-09-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_validity_period_docsobjects_end_eri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsobjects',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='docsobjects',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
