# Generated by Django 4.2.3 on 2023-09-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_docsobjects_file_alter_docsobjects_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsobjects',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='docsobjects',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
